routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Home
Route::view('/', 'welcome')->name('index');

// ABOUT
Route::view('/about', 'about')->name('about');

// Services
Route::prefix('services')->name('services.')->group(function() {
    // Services All
    Route::view('/best-digital-marketing-services-in-india','services')->name('all');
    Route::view('/best-ecommerce-website-development-company','services.ecommerce')->name('ecommerce');
    Route::view('/best-digital-marketing-company-in-india','services.digital-marketing')->name('digital-marketing');
    Route::view('/best-call-center-service-provider-in-india','services.call-center')->name('call-center');


});

// Contact US
Route::view('/contact-us', 'contact')->name('contact-us');
Route::post('send-mail','ContactController@sendMail')->name('contact.mail');

// Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/ContactController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class ContactController extends Controller
{
    /**
     * Send Contact Mail TO Admin And Thank You Mail TO Client
     * @param Request $request
     * @return Response Success or Fail
     * @author Shani Singh 
     */
    public function sendMail(Request $request)
    {
        dd($request->all());
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/about.blade.php
@extends('layouts.web')

@section('title')
    About AV E-Commerce Solutions
@endsection

@section('styles')
<!-- ==============================================
    Theme Settings
    =============================================== -->
<style>
        :root {               
            --header-bg-color: #040402;
            --nav-item-color: #f5f5f5;
            --hero-bg-color: #040402;

            --section-1-bg-color: #111111;
            --section-2-bg-color: #191919;
            --section-3-bg-color: #111111;
            --section-4-bg-color: #040402;
            --section-5-bg-color: #111111;
            --section-6-bg-color: #040402;
            --section-7-bg-color: #191919;
            --section-8-bg-color: #111111;
            --section-9-bg-color: #191919;
            --section-10-bg-color: #040402;
        
            --footer-bg-color: #111111;
        }
    </style>
@endsection

@section('content')

<!-- Hero -->
<section id="slider" class="hero p-0 odd featured">
    <div class="swiper-container no-slider slider-h-75">
        <div class="swiper-wrapper">

            <!-- Item 1 -->
            <div class="swiper-slide slide-center">

                <img src="{{asset('assets/images/bg-4.jpg')}}" class="full-image mask">

                <div class="slide-content row text-center">
                    <div class="col-12 mx-auto inner">
                        <h1 data-aos="zoom-out-up" data-aos-delay="400" class="title effect-static-text">ABOUT US</h1>
                        <nav data-aos="zoom-out-up" data-aos-delay="800" aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="{{route('index')}}">Home</a></li>
                                <li class="breadcrumb-item active" aria-current="page">About</li>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Single -->
<section id="single" class="section-1 single">
    <div class="container">
        <div class="row">
            <main class="col-12 col-lg-8 p-0">
                <div class="row">
                    <div class="col-12 align-self-center">
                        <h2 class="featured mt-0">About Us</h2>
                        <p>AV E-Commerce Solutions is an E-Commerce solution provider Company of Nagpur, India. We offer overall E-Commerce services like Making E-Commerce Store, Managing Social Media Marketing, Email Marketing, Customer Support etc.</p>
                        <p>We aim to provide research on client much needed online presence to generate maximum value and build the brand reputation online through E-Commerce channels. We are passionate about E-Commerce which gives effective business results for you.</p>
                        <p>
                            <blockquote>We are a full-service web-based E-Commerce Solution agency that develops websites and online internet campaigns also. We offer digital strategy, planning & creativity, resulting in fully managed and highly successful online marketing campaigns.</blockquote>
                        </p>
                        <p>We give you a sensible Internet marketing approach providing superior brand and user experiences that deliver the result to clients.</p>
                        <p>A Good eCommerce call centre gives a small business a big business feel.
                            We provide 24-hour sales, order entry, payment processing, billing inquiries, and more.</p>
                        <ul>
                            <li>E-Commerce Solutions</li>
                            <li>Digital Marketing</li>
                            <li>Call Center</li>
                        <ul>
                    </div>
                </div>
            </main>
            <aside class="col-12 col-lg-4 pl-lg-5 p-0 float-right sidebar">
                <div class="row">
                    <div class="col-12 align-self-center text-left">
                        <h4>Our Key Heighlights</h4>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item d-flex justify-content-center align-items-center">
                                <a href="#"><i class="icon icon-arrow-right"></i></a>
                                Best E-Commerce Solution Provider.
                            </li>
                            <li class="list-group-item d-flex justify-content-center align-items-center">
                                <a href="#l"><i class="icon icon-arrow-right"></i></a>
                                Best Digital Marketing Solution.
                            </li>
                            <li class="list-group-item d-flex justify-content-center align-items-center">
                                <a href="#"><i class="icon icon-arrow-right"></i></a>
                                Best Call Center Facility for E-Commerce.
                            </li>
                            <li class="list-group-item d-flex justify-content-center align-items-center">
                                <a href="#"><i class="icon icon-arrow-right"></i></a>
                                Expert Team member for each expertise domain.
                            </li>
                            <li class="list-group-item d-flex justify-content-center align-items-center">
                                <a href="#"><i class="icon icon-arrow-right"></i></a>
                                Best in class 24 X 7 Support for all customers.
                            </li>
                            <li class="list-group-item d-flex justify-content-center align-items-center">
                                <a href="#"><i class="icon icon-arrow-right"></i></a>
                                100% Customer Satisfaction in E-commerce and digital.
                            </li>
                        </ul>
                    </div>
                </div>
            </aside>
        </div>
    </div>
</section>

@include('partials.work')

@include('partials.team')

@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/partials/footer.blade.php
<footer>

    <!-- Footer [links] -->
    <section id="footer" class="odd footer">
        <div class="container">
            <div class="row">
                <div class="col-12 col-lg-3 p-3 text-center text-lg-left">
                    <div class="brand">
                        <a href="index.html" class="logo">
                           <img src="{{asset('images/logo.png')}}" alt="AV Ecommerce Solutions">
                        </a>
                    </div>
                    <p>Creative Ecommerce Solution Provider</p>
                </div>
                <div class="col-12 col-lg-3 p-3 text-center">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a href="{{ route('services.all') }}" class="nav-link">All Services</a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('services.ecommerce') }}" class="nav-link">E-commerce Service</a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('services.digital-marketing') }}" class="nav-link">Digital Marketing</a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('services.call-center') }}" class="nav-link">Call Center</a>
                        </li>
                    </ul>
                </div>
                <div class="col-12 col-lg-3 p-3 text-center">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a href="{{ route('about') }}" class="nav-link">About Us</a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('contact-us') }}" class="nav-link">Contact Us</a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">Follow Us</a>
                        </li>
                        <ul class="navbar-nav social share-list mt-0" style="margin-left: 60px;">
                            
                            <li class="nav-item">
                                <a href="https://www.facebook.com/avecommercesolutions" target="_blank" class="nav-link"><i class="icon-social-facebook ml-0"></i></a>
                            </li>
                            <li class="nav-item">
                                <a href="https://www.linkedin.com/company/av-e-commerce-solutions" target="_blank" class="nav-link"><i class="icon-social-linkedin"></i></a>
                            </li>
                            <li class="nav-item">
                                <a href="https://www.instagram.com/avecommercesolutions/" target="_blank" class="nav-link"><i class="icon-social-instagram "></i></a>
                            </li>
                            {{--  <li class="nav-item">
                                <a href="#" class="nav-link"><i class="icon-social-twitter"></i></a>
                            </li>  --}}
                        </ul>
                    </ul>
                </div>
                <div class="col-12 col-lg-3 p-3 text-center">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="icon-phone mr-2"></i>
                                +91 84088 66664
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="icon-envelope mr-2"></i>
                                avecommercesolutions@gmail.com
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="icon-location-pin mr-2"></i>
                                Jafar Nagar, Nagpur - 440013
                            </a>
                        </li>
                        {{--  <li class="nav-item">
                            <a href="{{ route('contact-us') }}" class="mt-4 ml-auto mr-auto btn primary-button"><i class="icon-phone"></i>Contact Us</a>
                        </li>  --}}
                    </ul>
                </div>
            </div>
        </div>
    </section>

    <!-- Copyright -->
    <section id="copyright" class="p-3 odd copyright">
        <div class="container">
            <div class="row">
                <div class="col-12 col-md-6 p-3 text-center text-lg-left">
                    <p>Best E-commerce Service provider.</p>
                </div>
                <div class="col-12 col-md-6 p-3 text-center text-lg-right">
                    <p>© 2020 AV E-commerce Solutions.</p>
                </div>
            </div>
        </div>
    </section>

</footer>

resources/views/partials/header.blade.php
<header id="header" class="odd">

    <!-- Navbar -->
    <nav data-aos="zoom-out" data-aos-delay="800" class="navbar navbar-expand">
        <div class="container header">

            <!-- Navbar Brand-->
            <a class="navbar-brand" href="{{route('index')}}">
                <img src="{{asset('images/logo.png')}}" alt="AV Ecommerce Solutions">
            </a>

            <!-- Nav holder -->
            <div class="ml-auto"></div>

            <!-- Navbar Items -->
            <ul class="navbar-nav items">
                <li class="nav-item {{Route::currentRouteName() == 'index' ? 'active' : ''}}">
                    <a href="{{route('index')}}" class="nav-link {{Route::currentRouteName() == 'index' ? 'active' : ''}}">Home</a>
                </li>
                <li class="nav-item {{Route::currentRouteName() == 'about' ? 'active' : ''}}">
                    <a href="{{route('about')}}" class="nav-link {{Route::currentRouteName() == 'about' ? 'active' : ''}}">About</a>
                </li>
                <li class="nav-item dropdown {{ Request::is('services/*') ? 'active' : '' }}">
                    <a href="{{ route('services.all') }}" class="nav-link {{ Request::is('services/*') ? 'active' : '' }}">Services <i class="icon-arrow-down"></i></a>
                    <ul class="dropdown-menu">
                        <li class="nav-item"><a href="{{ route('services.ecommerce') }}" class="nav-link {{ Request::is('services/*') ? 'active' : '' }}">E-commerce Solutions</a></li>
                        <li class="nav-item"><a href="{{ route('services.digital-marketing') }}" class="nav-link {{ Request::is('services/*') ? 'active' : '' }}">Digital Marketing</a></li>
                        <li class="nav-item"><a href="{{ route('services.call-center') }}" class="nav-link {{ Request::is('services/*') ? 'active' : '' }}">Call Center</a></li>
                    </ul>
                </li>
            </ul>

            <!-- Navbar Icons -->
            <ul class="navbar-nav icons">
                <li class="nav-item social">
                    <a href="https://www.facebook.com/avecommercesolutions" target="_blank" class="nav-link"><i class="icon-social-facebook"></i></a>
                </li>
                <li class="nav-item social">
                    <a href="https://www.linkedin.com/company/av-e-commerce-solutions" target="_blank" class="nav-link"><i class="icon-social-linkedin"></i></a>
                </li>
                <li class="nav-item social">
                    <a href="https://www.instagram.com/avecommercesolutions/" target="_blank" class="nav-link"><i class="icon-social-instagram"></i></a>
                </li>
            </ul>

            <!-- Navbar Toggle -->
            <ul class="navbar-nav toggle">
                <li class="nav-item">
                    <a href="#" class="nav-link" data-toggle="modal" data-target="#menu">
                        <i class="icon-menu m-0"></i>
                    </a>
                </li>
            </ul>

            <!-- Navbar Action -->
            <ul class="navbar-nav action">
                <li class="nav-item ml-3">
                    <a href="{{ route('contact-us') }}" class="btn ml-lg-auto dark-button"><i class="icon-phone"></i>CONTACT US</a>
                </li>
            </ul>
        </div>
    </nav>

</header>

resources/views/partials/services.blade.php
<!-- Services -->
<section id="services" class="section-4 odd offers featured">
    <div class="container">
        <div class="row intro">
            <div class="col-12 col-md-9 align-self-center text-center text-md-left">
                <h2 class="featured">Best Services</h2>
                <p>These are the area we hold expertise in, we believe in our great team effort and so would you. </p>
            </div>
            @if(!Request::is('services/*'))
            <div class="col-12 col-md-3 align-self-end">
                <a href="{{ route('services.all') }}" class="btn mx-auto mr-md-0 ml-md-auto primary-button"><i
                        class="icon-grid"></i>VIEW ALL</a>
            </div>
            @endif
        </div>
        <div class="row justify-content-center text-center items">
            <div class="col-12 col-md-6 col-lg-4 item">
                <a href="{{route('services.ecommerce')}}">
                    <div class="card featured">
                        <i class="icon icon-badge"></i>
                        <h4>E-Commerce Solutions</h4>
                        <p>We are passionate to provide the best ecommerce service that generates effective results.</p>
                        <i class="btn-icon icon-arrow-right-circle"></i>
                    </div>
                </a>
            </div>
            <div class="col-12 col-md-6 col-lg-4 item">
                <a href="{{route('services.digital-marketing')}}">
                    <div class="card">
                        <i class="icon icon-screen-tablet"></i>
                        <h4>Digital Marketing</h4>
                        <p>Our sensible and creative marketing approach can generate tremendous results for our client’s.</p>
                        <i class="btn-icon icon-arrow-right-circle"></i>
                    </div>
                </a>
            </div>
            <div class="col-12 col-md-6 col-lg-4 item">
                <a href="{{route('services.call-center')}}">
                    <div class="card featured">
                        <i class="icon icon-phone"></i>
                        <h4>Call Center</h4>
                        <p>We offer National and International call center service that runs 24 hours to provide endless support.</p>
                        <i class="btn-icon icon-arrow-right-circle"></i>
                    </div>
                </a>
            </div>
        </div>
    </div>
</section>

resources/views/services/call-center.blade.php
@extends('layouts.web')

@section('title')
    Best BPO Call Center Provider In India
@endsection

@section('styles')
<style>
    :root {
        --header-bg-color: #111111;
        --nav-item-color: #f5f5f5;
        --hero-bg-color: #111111;

        --section-1-bg-color: #eeeeee;
    
        --footer-bg-color: #111111;
    }

    .odd h2{
        color: #2f323a;
    }
</style>
@endsection

@section('content')
<!-- Hero -->
<section id="slider" class="hero p-0 odd featured">
    <div class="swiper-container no-slider slider-h-75">
        <div class="swiper-wrapper">

            <!-- Item 1 -->
            <div class="swiper-slide slide-center">

                <img data-aos="zoom-out-up" data-aos-delay="800" src="{{asset('images/services/call1.jpg')}}" class="full-image">
                
                <div class="slide-content row text-center">
                    <div class="col-12 mx-auto inner">
                        <h1 data-aos="zoom-out-up" data-aos-delay="400" class="title effect-static-text">BPO Call Center</h1>
                        <nav data-aos="zoom-out-up" data-aos-delay="800" aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="{{ route('index') }}">Home</a></li>
                                <li class="breadcrumb-item"><a href="{{ route('services.all') }}">Services</a></li>
                                <li class="breadcrumb-item active" aria-current="page">BPO Call Center</li>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Single -->
<section id="blog" class="section-1 single">
    <div class="container">
        <div class="row content">
            <main class="col-12 col-lg-8 p-0">

                <!-- Text -->
                <div class="row">
                    <div class="col-12 align-self-center">
                        <h2 class="featured mt-0">BPO Call Center</h2>
                        <p>AV E-commerce Solutions works 24x7 to provide services to its clients. By putting enormous effort and dedication, our team provides 24-hour sales, order entries, payment processing, billing inquiries, and more.</p>
                        <p>By adopting a research-led approach, AV Ecommerce Silutions equips organizations with powerful insights that can transform the way they perceive business challenges. Our teams consists of domain-specific experts who can help companies develop innovative strategies in order to compete and win in the industry segment they operate.</p>
                        <p>
                            <blockquote>we do support Brands to track their Customer Engagement through our extensive platform. Companies can monitor their Net Promoter Score [NPS], Customer Satisfaction [CSAT] levels as well the Customer Engagement through Email, Chat, and Social Media channels. Syrow BrandLabs provide tools to track and measure the metrics that are more important for an Organisation to deliver incredible Customer Service in a fraction of the time.</blockquote>
                        </p>
                        <div class="gallery">
                            <a href="{{asset('images/services/call.jpg')}}">
                                <img src="{{asset('images/services/call.jpg')}}" class="w-100">
                            </a>
                        </div>

                        <h4>Our Promise</h4>
                        <p>Implement Order Management Process: Enable real-time updates about the products. Advertise them on different platforms. Manage, monitor, and optimize the activity.</p>
                        <ul>
                            <li>eCommerce Website Design Services</li>
                            <li>eCommerce Website Development Services</li>
                            <li>eCommerce SEO Services for eCommerce Websites</li>
                            <li>Payment Gateways</li>
                            <li>eCommerce Fulfillment Services</li>
                        <ul>

                        <h4>
                            Currently, we are working on the Australian process.
                            In a case on any query please feel free to contact us.
                        </h4>
                    </div>
                </div>

            </main>
            <aside class="col-12 col-lg-4 pl-lg-5 p-0 float-right sidebar">
                
                         
                
                <!-- Features -->
                <div class="row item">
                    <div class="col-12 align-self-center">
                        <h4>Features</h4>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                <a href="#">Experienced Workforce: Our team has the right knowledge and skill to handle your Customer queries.</a>
                                <i class="icon-check"></i>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                <a href="#">Professional Call Handling: Our team is trained with the right behavior and etiquette to provide a great Customer eXperience.</a>
                                <i class="icon-check"></i>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                <a href="#">Quick Resolution of Escalations: We provide resolution to escalations with short turnaround time adhering to the Client SLA’s.</a>
                                <i class="icon-check"></i>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                <a href="#">Timely Updates for Decision Making: We help you to get timely updates for decision making that significantly supports business.</a>
                                <i class="icon-check"></i>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                <a href="#">Improved Customer Satisfaction: We enhance Customer eXperience “inside-out” by being the human face of Business.</a>
                                <i class="icon-check"></i>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                <a href="#">Significant Cost Savings: We account to significant cost savings by providing effective solution at affordable price.</a>
                                <i class="icon-check"></i>
                            </li>
                        </ul>
                    </div>
                </div>


                
                <!-- Tags -->
                <div class="row item">
                    <div class="col-12 align-self-center">
                        <h4>Tags</h4>
                        <div class="ml--03">
                            <span class="badge tag active">Customer Service</span>
                            <span class="badge tag active">24 X 7 Inbound Call</span>
                            <span class="badge tag active">Semi Voice</span>
                            <span class="badge tag active">24 X 7 Email, Chat</span>
                            <span class="badge tag active">Tele Calling Service</span>
                            <span class="badge tag active">Outbound Calls</span>
                        </div>
                    </div>
                </div>

                <!-- Follow Us -->
                <div class="row item">
                    <div class="col-12 align-self-center">
                        <h4>Follow Us</h4>
                        <ul class="navbar-nav social share-list">
                            <li class="nav-item">
                                <a href="#" class="nav-link"><i class="icon-social-instagram ml-0"></i></a>
                            </li>
                            <li class="nav-item">
                                <a href="#" class="nav-link"><i class="icon-social-facebook"></i></a>
                            </li>
                            <li class="nav-item">
                                <a href="#" class="nav-link"><i class="icon-social-linkedin"></i></a>
                            </li>
                            <li class="nav-item">
                                <a href="#" class="nav-link"><i class="icon-social-twitter"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>  

            </aside>
        </div>
    </div>
</section>

@endsection